# This is a basic workflow to help you get started with Actions

name: CI

env:
  DotNetVersion: 6.0.100-preview.2.21155.3
  AndroidMsi: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4534967/main/f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2/Microsoft.NET.Workload.Android.11.0.200.148.msi
  AndroidPkg: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4534967/main/f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2/Microsoft.NET.Workload.Android-11.0.200-ci.f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2.148.pkg
  iOSMsi: https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/Microsoft.NET.Workload.iOS.14.4.100-ci.main.1192.msi
  iOSPkg: https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/notarized/Microsoft.iOS.Bundle.14.4.100-ci.main.1192.pkg
  MacCatalystPkg: https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/notarized/Microsoft.MacCatalyst.Bundle.14.3.100-ci.main.337.pkg

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install DotNet Preview
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
          & .\dotnet-install.ps1 -Version $env:DotNetVersion -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
          & dotnet --list-sdks
          
          & dotnet tool install --global boots --add-source "https://api.nuget.org/v3/index.json"
          & boots $env:AndroidMsi
          & boots $env:iOSMsi
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  build-mac:
    runs-on: macos-latest

    steps:
    
      - name: Install DotNet Preview
        shell: bash
        run: >
          export PATH="/usr/local/share/dotnet/:~/.dotnet/tools:$PATH" &&
          curl -L https://raw.githubusercontent.com/dotnet/install-scripts/7a9d5dcab92cf131fc2d8977052f8c2c2d540e22/src/dotnet-install.sh > dotnet-install.sh &&
          sh dotnet-install.sh --version 6.0.100-preview.2.21155.3 --install-dir $DOTNET_ROOT --verbose &&
          dotnet --list-sdks &&
          echo "##vso[task.setvariable variable=PATH]$PATH"

      - name: Install Mobile
        shell: pwsh
        run: |
           & dotnet tool install --global boots --add-source "https://api.nuget.org/v3/index.json"
           & boots $env:AndroidPkg
           & boots $env:iOSPkg
           & boots $env:MacCatalystPkg
